// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbbQS8ZyzDzclqtjWwgQ1yK1QMtCcjzVE',
    appId: '1:979113230125:web:2879bb4ce32adae9525da4',
    messagingSenderId: '979113230125',
    projectId: 'fir-flutter-codelab-b6c17',
    authDomain: 'fir-flutter-codelab-b6c17.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-b6c17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFvlPgdewXtJC_1XjO0q23Z2Eeo_3yzFE',
    appId: '1:979113230125:android:31cdfba590d68554525da4',
    messagingSenderId: '979113230125',
    projectId: 'fir-flutter-codelab-b6c17',
    storageBucket: 'fir-flutter-codelab-b6c17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnZD9tNj0HWmXgdV7OKFL8byCp8oubup8',
    appId: '1:979113230125:ios:6066adf7e2afd3fb525da4',
    messagingSenderId: '979113230125',
    projectId: 'fir-flutter-codelab-b6c17',
    storageBucket: 'fir-flutter-codelab-b6c17.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnZD9tNj0HWmXgdV7OKFL8byCp8oubup8',
    appId: '1:979113230125:ios:6066adf7e2afd3fb525da4',
    messagingSenderId: '979113230125',
    projectId: 'fir-flutter-codelab-b6c17',
    storageBucket: 'fir-flutter-codelab-b6c17.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
